### ISSUE TITLE
i am getting memory error on chapter 09

### ISSUE THREAD

**Issue by BAG-OF-CHIPS-XX** [PacktPublishing/Keras-Deep-Learning-Cookbook#3]
I did the math and it would take over 3000gigs of ram to run the code in ch09.

Loaded Stories 568411
<class 'list'>
Number of samples: 568411
Number of unique input tokens: 84
Number of unique output tokens: 48
Max sequence length for inputs: 15074
Max sequence length for outputs: 5
Approx size 719731102776
C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\cdang\Desktop\GitHub_Projects\Keras-Deep-Learning-Cookbook\Chapter09\lstm_seq2seq.py", line 115, in <module>
    dtype=np.float16)
MemoryError

**Comment by abhineet99** [comment]
same issue

**Comment by areejokaili** [comment]
I'm not sure if you have already solved this but here is one simple solution. You can load the data to an array on disk instead of loading the whole data to memory. 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html
